const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FALSE: "FETCH_GENDER_FALSE",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FALSE: "FETCH_POSITION_FALSE",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FALSE: "FETCH_ROLE_FALSE",

  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAILED: "SAVE_USER_FAILED",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

  FETCH_REQUIRED_DOCTOR_INFO_FAILED: "FETCH_REQUIRED_DOCTOR_INFO_FAILED",
  FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: "FETCH_REQUIRED_DOCTOR_INFO_SUCCESS",

  CANCEL_UPDATE_USERS: "CANCEL_UPDATE_USERS",

  //user
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  DETAIL_DOCTOR_SUCCESS: "DETAIL_DOCTOR_SUCCESS",
  DETAIL_DOCTOR_FAILED: "DETAIL_DOCTOR_FAILED",
  FETCH_SCHEDULE_DOCTOR_SUCCESS: "FETCH_SCHEDULE_DOCTOR_SUCCESS",
  FETCH_SCHEDULE_DOCTOR_FAILED: "FETCH_SCHEDULE_DOCTOR_FAILED",
  FETCH_PROFILE_DOCTOR_BY_ID_SUCCESS: "FETCH_PROFILE_DOCTOR_BY_ID_SUCCESS",
  FETCH_PROFILE_DOCTOR_BY_ID_FAILED: "FETCH_PROFILE_DOCTOR_BY_ID_FAILED",

  FETCH_EXTRA_DOCTOR_INFO_SUCCESS: "FETCH_EXTRA_DOCTOR_INFO_SUCCESS",
  FETCH_EXTRA_DOCTOR_INFO_FAILED: "FETCH_EXTRA_DOCTOR_INFO_FAILED",

  // Doctor
  FETCH_TOP_DOCTOR_HOME_SUCCESS: "FETCH_TOP_DOCTOR_HOME_SUCCESS",
  FETCH_TOP_DOCTOR_HOME_FAILED: "FETCH_TOP_DOCTOR_HOME_FAILED",

  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAILED: "FETCH_ALL_DOCTOR_FAILED",

  SAVE_MARK_DOCTOR_SUCCESS: "SAVE_MARK_DOCTOR_SUCCESS",
  SAVE_MARK_DOCTOR_FAILED: "SAVE_MARK_DOCTOR_FAILED",
  GET_MARKDOWN_DOCTOR_SUCCESS: "GET_MARKDOWN_DOCTOR_SUCCESS",
  GET_MARKDOWN_DOCTOR_FAILED: "GET_MARKDOWN_DOCTOR_FAILED",
  UPDATE_MARKDOWN_DOCTOR_SUCCESS: "UPDATE_MARKDOWN_DOCTOR_SUCCESS",
  UPDATE_MARKDOWN_DOCTOR_FAILED: "UPDATE_MARKDOWN_DOCTOR_FAILED",

  FETCH_ALLCODE_SCHEDULE_HOUR_SUCCESS: "FETCH_ALLCODE_SCHEDULE_HOUR_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_HOUR_FAILED: "FETCH_ALLCODE_SCHEDULE_HOUR_FAILED",

  TOGGLE_RANGE_TIME_SCHEDULE_SUCCESS: "TOGGLE_RANGE_TIME_SCHEDULE_SUCCESS",
  TOGGLE_RANGE_TIME_SCHEDULE_FAILED: "TOGGLE_RANGE_TIME_SCHEDULE_FAILED",

  POST_BOOKING_APPOINTMENT_SUCCESS: "POST_BOOKING_APPOINTMENT_SUCCESS",
  POST_BOOKING_APPOINTMENT_FAILED: "POST_BOOKING_APPOINTMENT_FAILED",

  CONFIRM_BOOKING_APPOINTMENT_SUCCESS: "CONFIRM_BOOKING_APPOINTMENT_SUCCESS",
  CONFIRM_BOOKING_APPOINTMENT_FAILED: "CONFIRM_BOOKING_APPOINTMENT_FAILED",

  IS_DETAIL_DOCTOR: "IS_DETAIL_DOCTOR ",

  // toatify
  INCREMENT: "INCREMENT",
  DECREASE: "DECREASE",
});

export default actionTypes;
